Repository maple-labs/liquidations, pull requests merged in 2021-12, with the labels that each got.

#8 feat: Add require on transfer and EOA OTC liquidation test (SC-4180)
  contracts/Liquidator.sol
  contracts/test/Liquidator.t.sol
Labels: Priority: High, Status: Ready for Review

#10 feat: Add max return amount
  contracts/Liquidator.sol
  contracts/SushiswapStrategy.sol
  contracts/UniswapV2Strategy.sol
  contracts/interfaces/ILiquidator.sol
  contracts/interfaces/IUniswapV2StyleStrategy.sol
  contracts/interfaces/Interfaces.sol
  contracts/test/Liquidator.t.sol
Labels: Status: Ready for Review

#15 fix: Add input validation to constructor (SC-4265)
  contracts/Liquidator.sol
  contracts/test/Liquidator.t.sol
Labels: Status: Ready for Review

#16 feat: Pause functionality + reentrancy modifier (SC-4270)
  contracts/Liquidator.sol
  contracts/SushiswapStrategy.sol
  contracts/UniswapV2Strategy.sol
  contracts/interfaces/ILiquidator.sol
  contracts/interfaces/IUniswapV2StyleStrategy.sol
  contracts/interfaces/Interfaces.sol
  contracts/test/Liquidator.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Status: Ready for Review

#18 fix: Strict 0.8.7 (C4 #23)
  contracts/test/Liquidator.t.sol
  contracts/test/accounts/Owner.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#19 fix: Constructor Input Validation (SC-4297)
  contracts/Liquidator.sol
  contracts/test/Liquidator.t.sol
Labels: Priority: Medium, Status: Ready for Review

#20 fix: Shorten require messages (C4 #3)
  contracts/SushiswapStrategy.sol
  contracts/UniswapV2Strategy.sol
Labels: Priority: Medium, Status: Ready for Review

#21 fix: Reentrancy optimization (C4 #64)
  contracts/Liquidator.sol
Labels: Priority: Medium, Status: Ready for Review

#22 fix: Use constant instead of block.timestamp (C4 #55)
  contracts/SushiswapStrategy.sol
  contracts/UniswapV2Strategy.sol
Labels: Priority: Medium, Status: Ready for Review

#23 fix: Unchecked approve (C4 #52)
  contracts/SushiswapStrategy.sol
  contracts/UniswapV2Strategy.sol
Labels: Priority: Medium, Status: Ready for Review

#24 fix: Use immutables (C4 #7)
  contracts/Liquidator.sol
Labels: Priority: Medium, Status: Ready for Review

#25 chore: cleanup
  .gitmodules
  contracts/interfaces/ILiquidator.sol
  contracts/interfaces/IUniswapV2StyleStrategy.sol
  contracts/interfaces/Interfaces.sol
  contracts/test/Liquidator.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#26 fix: Balance check in swap function can cause DoS (c4 #35)
  contracts/SushiswapStrategy.sol
  contracts/UniswapV2Strategy.sol
Labels: Priority: Medium, Status: Ready for Review

#27 feat: Improve strategy and cleanup
  contracts/SushiswapStrategy.sol
  contracts/UniswapV2Strategy.sol
  contracts/interfaces/IUniswapV2StyleStrategy.sol
  contracts/interfaces/Interfaces.sol
  contracts/test/Liquidator.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review
